title: Nodetator
email: nodetator@gmail.com
description: Nodetator's website
url: "https://nodetator.xyz"
twitter: NodeTator

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed